# Generated by Django 2.2.16 on 2022-11-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите понятное название ингредиента.', max_length=1000, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Напишите что понравится, от чайной ложки до ковша экскаватора.', max_length=1000, verbose_name='Единицы измерения ингредиента')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество ингредиента')),
            ],
            options={
                'default_related_name': 'ingridientsquantity',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Придумайте название рецепта,отражающее его суть или просто интересное название :)', max_length=255, verbose_name='Название рецепта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Картинка')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text=('Укажите примерное время,необходимое для приготовления Вашего блюда.',), verbose_name='Время приготовления')),
                ('text', models.TextField(help_text='Напишите рецепт блюда,чтобы его смог приготовить любой желающий!', verbose_name='Описание рецепта')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категория к которой Вы бы отнесли свой рецепт.Одним словом.', max_length=100, verbose_name='Тег рецепта')),
                ('slug', models.SlugField(help_text='Добавьте уникальный ID для тега', unique=True, verbose_name='Уникальное название тега')),
                ('color', models.CharField(default='#ffffff', max_length=7)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            options={
                'verbose_name': 'Список покупок',
            },
        ),
    ]
