# Generated by Django 3.2.16 on 2022-11-22 14:28

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221118_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='От чайной ложки до ковша экскаватора.', max_length=1000, verbose_name='Единицы измерения ингредиента'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=7, samples=None, unique=True, verbose_name='HEX-код цвета'),
        ),
    ]
