# Generated by Django 3.2.16 on 2022-11-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221122_2028'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientquantity',
            name='quantity_gte_1',
        ),
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AddConstraint(
            model_name='ingredientquantity',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 1)), name='amount_gte_1'),
        ),
    ]
